name: GitHub Pages

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensure the token has write permissions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Adjust this to your build output directory if needed
